# yaml-language-server: $schema=https://raw.githubusercontent.com/readthedocs/readthedocs.org/master/readthedocs/rtd_tests/fixtures/spec/v2/schema.json
# ref: <https://docs.readthedocs.com/platform/stable/config-file/v2.html>

version: 2

python:
  install:
    - requirements: requirements.txt

build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  jobs:
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      - uv venv "$READTHEDOCS_VIRTUALENV_PATH"
    install:
      - UV_PROJECT_ENVIRONMENT="$READTHEDOCS_VIRTUALENV_PATH" uv sync --all-extras --all-groups --link-mode copy
    pre_build:
      - if test -f "docs/scripts/pre-build.sh"; then bash "docs/scripts/pre-build.sh"; fi

mkdocs:
  configuration: mkdocs.yaml
