#:schema https://json.schemastore.org/ruff.json
extend = ".github/linters/.ruff.toml"
target-version = "py312"

[lint]
extend-ignore = ["E741", "F722", "FBT003", "N802", "N803", "N806", "PLC2401"]

[lint.flake8-import-conventions.extend-aliases]
"avocado" = "ac"
"banana" = "bn"
"comet_ml" = "comet"
"grapes" = "gr"
