#!/bin/bash
# This file is @generated by <https://github.com/liblaf/copier-python>.
# DO NOT EDIT!

if [[ -f "pixi.lock" ]]; then
  args=()
  if [[ -t 2 ]]; then args+=(--color=always); fi
  "$(pixi shell-hook "${args[@]}")"
fi

if [[ -f "uv.lock" ]]; then
  uv sync --all-extras --all-groups
  # shellcheck disable=SC1091
  source ".venv/bin/activate"
fi
