# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# prettier-ignore
_commit: 8f0ca6e
_src_path: gh:liblaf/copier-python
author: liblaf
email: 30631553+liblaf@users.noreply.github.com
license: MIT
name: liblaf.grapes
owner: liblaf
package_manager: pixi
repo: grapes
