name: Docs (stable)

on:
  push:
    tags:
      - v*
  release:
    types:
      - published

jobs:
  docs:
    name: Docs
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-docs
      cancel-in-progress: true
    steps:
      - id: auth
        name: Auth App
        uses: liblaf/actions/auth-app@main
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.auth.outputs.token }}
          fetch-depth: 0
      - name: Fetch `gh-pages`
        # ref: <https://github.com/jimporter/mike?tab=readme-ov-file#deploying-via-ci>
        run: git fetch origin gh-pages --depth=1
      - name: Setup Python
        uses: liblaf/actions/setup-python@main
        with:
          python-version: ${{ vars.PYTHON_VERSION || '3.12' }}
      - if: hashFiles('docs/scripts/prepare.sh') != ''
        name: Prepare
        run: docs/scripts/prepare.sh
      - id: version
        name: SemVer Parse
        uses: liblaf/actions/semver-parse@main
        with:
          version: ${{ github.ref_name }}
      - name: Deploy
        run: mike deploy --push "$MAJOR.$MINOR" stable
        env:
          MAJOR: ${{ steps.version.outputs.major }}
          MINOR: ${{ steps.version.outputs.minor }}
