name: Docs (dev)

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Docs
    permissions:
      contents: write
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-docs
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch `gh-pages`
        run: git fetch origin gh-pages --depth=1
      - name: Configure Git User
        run: |-
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Setup Python
        uses: liblaf/actions/setup-python@main
      - if: hashFiles('docs/scripts/prepare.sh') != ''
        name: Prepare
        run: docs/scripts/prepare.sh
      - name: Deploy
        run: mike deploy --push dev
      - name: Set Default
        run: mike set-default --push dev
